[versions]
opentelemetry-logback-appender = "2.28.0-alpha"

[libraries]
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-opentelemetry = { module = "org.springframework.boot:spring-boot-starter-opentelemetry" }

testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql" }
testcontainers-rabbitmq = { module = "org.testcontainers:testcontainers-rabbitmq" }

micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus" }
micrometer-tracing-bridge-otel = { module = "io.micrometer:micrometer-tracing-bridge-otel" }
opentelemetry-logback-appender = { module = "io.opentelemetry.instrumentation:opentelemetry-logback-appender-1.0", version.ref = "opentelemetry-logback-appender" }

[bundles]
# Language neutral: safe for Java-only, Kotlin-only and mixed services.
spring-web = [
    "spring-boot-starter-web",
    "spring-boot-starter-validation"
]
siloverse-observability = [
    "micrometer-registry-prometheus",
    "micrometer-tracing-bridge-otel",
    "spring-boot-starter-opentelemetry",
    "opentelemetry-logback-appender",
    "spring-boot-starter-actuator"
]